import { createRouter, createWebHistory } from 'vue-router'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
      {
        path:"/",
        name:"layout",
        component:()=>import("@/views/Layout.vue"),
        children:[
        {
          path:"/",
          name:"首页",
          component:()=>import("@/views/Index/index.vue"),
        },
        {
          path:"/user/:userId",
          name:"用户信息",
          component:()=>import("@/views/User/user.vue"),
        },
        {
          path:"/user/message/:type",
          name:"消息中心",
          component:()=>import("@/views/User/MesssageList.vue"),
        },
        {
          path:"/destination",
          name:"目的地",
          component:()=>import("@/views/Destination/destination.vue"),
        },
        {
          path:"/destination/:regionId",
          name:"线路",
          component:()=>import("@/views/Destination/lineList.vue"),
        },
        {
          path:"/tips",
          name:"旅游攻略",
          component:()=>import("@/views/Tips/tips.vue"),
        },
        {
          path:"/tips/:regionsId/",
          name:"旅游攻略板块",
          component:()=>import("@/views/Tips/tipsList.vue"),
        },
        {
          path:"/trip",
          name:"去旅行",
          component:()=>import("@/views/Trip/trip.vue"),
        },
        {
          path:"/trip/:query",
          name:"旅行查询",
          component:()=>import("@/views/Trip/tripList.vue"),
        },
        {
          path:"/trip/detail/:salesId/",
          name:"景点详情",
          component:()=>import("@/views/Trip/tripDetail.vue"),
        },
        {
          path:"/hotel",
          name:"订酒店",
          component:()=>import("@/views/Hotel/hotel.vue"),
        },
        {
          path:"/community",
          name:"社区",
          component:()=>import("@/views/Community/community.vue"),
        },
        {
          path:"/newPost",
          name:"发帖",
          component:()=>import("@/views/ArticleItem/EditPost.vue"),
        },
        {
          path:"/editPost/:articleId",
          name:"编辑文章",
          component:()=>import("@/views/ArticleItem/EditPost.vue"),
        },
        {
          path:"/article/:articleId/",
          name:"文章详情",
          component:()=>import("@/views/ArticleItem/ArticleDetail.vue"),
        },
        {
          path:"/order/:saleId/",
          name:"订单",
          component:()=>import("@/views/Order/Order.vue"),
        },
        {
          path:"/orderSuccess/:orderId/",
          name:"订单成功页面",
          component:()=>import("@/views/Order/OrderSuccess.vue"),
        },
      ]
      },
      {
        path:"/:pathMatch(.*)*",
        name:"错误页",
        component:()=>import("@/views/Error404.vue")
      }
  ]
})

export default router
